# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dict.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_widget(object):
    def setupUi(self, widget):
        widget.setObjectName("widget")
        widget.resize(505, 380)
        self.gridLayout = QtWidgets.QGridLayout(widget)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.explanation = QtWidgets.QTextBrowser(widget)
        self.explanation.setObjectName("explanation")
        self.verticalLayout.addWidget(self.explanation)
        self.example = QtWidgets.QTextBrowser(widget)
        self.example.setObjectName("example")
        self.verticalLayout.addWidget(self.example)
        self.synonyms = QtWidgets.QTextBrowser(widget)
        self.synonyms.setObjectName("synonyms")
        self.verticalLayout.addWidget(self.synonyms)
        self.gridLayout.addLayout(self.verticalLayout, 1, 0, 1, 5)
        self.backpage = QtWidgets.QPushButton(widget)
        self.backpage.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.backpage.sizePolicy().hasHeightForWidth())
        self.backpage.setSizePolicy(sizePolicy)
        self.backpage.setObjectName("backpage")
        self.gridLayout.addWidget(self.backpage, 0, 2, 1, 1)
        self.findword = QtWidgets.QPushButton(widget)
        self.findword.setObjectName("findword")
        self.gridLayout.addWidget(self.findword, 0, 1, 1, 1)
        self.nextpage = QtWidgets.QPushButton(widget)
        self.nextpage.setEnabled(False)
        self.nextpage.setObjectName("nextpage")
        self.gridLayout.addWidget(self.nextpage, 0, 4, 1, 1)
        self.entersign = QtWidgets.QLineEdit(widget)
        self.entersign.setClearButtonEnabled(True)
        self.entersign.setObjectName("entersign")
        self.gridLayout.addWidget(self.entersign, 0, 0, 1, 1)
        self.pagesize = QtWidgets.QComboBox(widget)
        self.pagesize.setEnabled(False)
        self.pagesize.setObjectName("pagesize")
        self.gridLayout.addWidget(self.pagesize, 0, 3, 1, 1)

        self.retranslateUi(widget)
        QtCore.QMetaObject.connectSlotsByName(widget)

    def retranslateUi(self, widget):
        _translate = QtCore.QCoreApplication.translate
        widget.setWindowTitle(_translate("widget", "Primus Dictionary 1.0"))
        self.backpage.setText(_translate("widget", "<"))
        self.findword.setText(_translate("widget", "Find!"))
        self.nextpage.setText(_translate("widget", ">"))
        self.entersign.setText(_translate("widget", "Enter a word..."))
